language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gregvinton/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gregvinton/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: DockerReact-env
  bucket_name: "elasticbeanstalk-ap-southeast-2-930677577891"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_KEY

    